package com.ranger.common;

public class SQLConstant {

	public static final String TAG_INSERT = "INSERT INTO WB_TAG(`ID`, `TID`, `VALUE`, `WEIGHT`, `USER_ID`) VALUES(?,?,?,?,?)";
	public static final String TAG_SELECT = "SELECT `ID`, `TID`, `VALUE`, `WEIGHT`, `USER_ID` FROM `WB_TAG` ";
	
	public static final String USER_INSERT = "INSERT INTO WB_USER(`ID`, `UID`, `SCREEN_NAME`, `NAME`, `PROVINCE`, `CITY`, `LOCATION`, `DESCRIPTION`, `URL`, `PROFILE_IMAGE_URL`, " +
			"`USER_DOMAIN`, `GENDER`, `FOLLOWERS_COUNT`, `FRIENDS_COUNT`, `STATUSES_COUNT`, `FAVOURITES_COUNT`, `CREATE_AT`, `FOLLOWING`, `VERIFIED`, " +
			"`VERIFIED_TYPE`, `ALLOW_ALL_ACT_MSG`, `ALLOW_ALL_COMMENT`, `FOLLOW_ME`, `AVATAR_LARGE`, `ONLINE_STATUS`, `BI_FOLLOWERS_COUNT`, `REMARK`, " +
			"`LANG`, `VERIFIED_REASON`, `WEIHAO`, `STATUS_ID`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String USER_SELECT = "SELECT ID, `UID`, `SCREEN_NAME`, `NAME`, `PROVINCE`, `CITY`, `LOCATION`, `DESCRIPTION`, `URL`, `PROFILE_IMAGE_URL`, " +
			"`USER_DOMAIN`, `GENDER`, `FOLLOWERS_COUNT`, `FRIENDS_COUNT`, `STATUSES_COUNT`, `FAVOURITES_COUNT`, `CREATE_AT`, `FOLLOWING`, `VERIFIED`, " +
			"`VERIFIED_TYPE`, `ALLOW_ALL_ACT_MSG`, `ALLOW_ALL_COMMENT`, `FOLLOW_ME`, `AVATAR_LARGE`, `ONLINE_STATUS`, `BI_FOLLOWERS_COUNT`, `REMARK`, " +
			"`LANG`, `VERIFIED_REASON`, `WEIHAO`, `STATUS_ID` FROM `WB_USER` ";
	
	public static final String VISIBLE_INSERT = "INSERT INTO WB_VISIBLE(`ID`, `TYPE`, `LIST_ID`) VALUES(?,?,?)";
	public static final String VISIBLE_SELECT = "SELECT `ID`, `TYPE`, `LIST_ID`) FROM `WB_VISIBLE` ";
	
	public static final String SOURCE_INSERT = "INSERT INTO `WB_SOURCE` (`ID`, `URL`, `RELATIONSHIP`, `NAME`) VALUES(?,?,?,?)";
	public static final String SOURCE_SELECT = "SELECT `ID`, `URL`, `RELATIONSHIP`, `NAME` FROM `WB_SOURCE` ";
	
	public static final String STATUS_INSERT = "INSERT INTO WB_STATUS(`ID`, `STID`,`USER_ID`,`CREATE_AT`,`MID`,`ID_STR`,`TEXT`,`SR_ID`,`FAVORRITED`,`TRUNCATED`,`IN_REPLY_TO_STATUS_ID`," +
			"`IN_REPLY_TO_USER_ID`,`IN_REPLY_TO_SCREEN_NAME`,`THUNMB_NAIL_PIC`,`B_MIDDLE_PIC`,`RETWEETED_STATUS_ID`,`GEO`," + 
			"`LATITUDE`,`LONGITUDE`,`REPORTS_COUNT`,`COMMENTS_COUNT`,`ANNOTATIONS`,`M_LEVEL`,`V_ID`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String STATUS_SELECT = "SELECT `ID`, `STID`,`USER_ID`,`CREATE_AT`,`MID`,`ID_STR`,`TEXT`,`SR_ID`,`FAVORRITED`,`TRUNCATED`,`IN_REPLY_TO_STATUS_ID`," +
			"`IN_REPLY_TO_USER_ID`,`IN_REPLY_TO_SCREEN_NAME`,`THUNMB_NAIL_PIC`,`B_MIDDLE_PIC`,`RETWEETED_STATUS_ID`,`GEO`," + 
			"`LATITUDE`,`LONGITUDE`,`REPORTS_COUNT`,`COMMENTS_COUNT`,`ANNOTATIONS`,`M_LEVEL`,`V_ID` FROM `WB_STATUS` ";
	
	
}