SET PASSWORD FOR 'root'@'localhost' = PASSWORD('dilip987');
SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('dilip987');

CREATE DATABASE IF NOT EXISTS `ranger`;
CREATE USER 'rangeruser'@'%' IDENTIFIED BY PASSWORD '*ACBBAB38251D9F16850BC013ECFD77F4B063346A';
CREATE USER 'rangeruser'@'localhost' IDENTIFIED BY PASSWORD '*ACBBAB38251D9F16850BC013ECFD77F4B063346A';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, TRIGGER ON `ranger`.* TO 'rangeruser'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, TRIGGER ON `ranger`.* TO 'rangeruser'@'localhost';

use ranger;

CREATE TABLE `WB_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` char(50) NOT NULL,
  `SCREEN_NAME` varchar(100) NOT NULL,
  `NAME` varchar(200) NOT NULL,
  `PROVINCE` int(11) DEFAULT '-1',
  `CITY` int(11) DEFAULT '-1',
  `LOCATION` varchar(200) DEFAULT '',
  `DESCRIPTION` varchar(200) DEFAULT '',
  `URL` varchar(200) DEFAULT '',
  `PROFILE_IMAGE_URL` varchar(200) DEFAULT '',
  `USER_DOMAIN` varchar(100) DEFAULT '',
  `GENDER` char(1) DEFAULT 'N',
  `FOLLOWERS_COUNT` int(11) DEFAULT '0',
  `FRIENDS_COUNT` int(11) DEFAULT '0',
  `STATUSES_COUNT` int(11) DEFAULT '0',
  `FAVOURITES_COUNT` int(11) DEFAULT '0',
  `CREATE_AT` datetime DEFAULT NULL,
  `FOLLOWING` char(1) DEFAULT 'N',
  `VERIFIED` char(1) DEFAULT 'N',
  `VERIFIED_TYPE` int(11) DEFAULT '-1',
  `ALLOW_ALL_ACT_MSG` char(1) DEFAULT 'N',
  `ALLOW_ALL_COMMENT` char(1) DEFAULT 'N',
  `FOLLOW_ME` char(1) DEFAULT 'N',
  `AVATAR_LARGE` varchar(200) DEFAULT '',
  `ONLINE_STATUS` int(11) DEFAULT '-1',
  `BI_FOLLOWERS_COUNT` int(11) DEFAULT '0',
  `REMARK` varchar(500) DEFAULT '',
  `LANG` char(10) DEFAULT 'ZH-CN',
  `VERIFIED_REASON` varchar(100) DEFAULT '',
  `WEIHAO` varchar(50) DEFAULT '',
  `STATUS_ID` char(10) DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_UNIQUE` (`UID`)
);

use ranger;

CREATE TABLE `WB_TAG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TID` char(20) NOT NULL,
  `VALUE` varchar(200) NOT NULL,
  `WEIGHT` varchar(200) NOT NULL,
  `USER_ID` bigint(20) DEFAULT NULL, -- user db primary key id, not the unique user uid
  PRIMARY KEY (`ID`),
  -- UNIQUE KEY `TID_UNIQUE` (`TID`),
  CONSTRAINT `USER_ID_TAG` FOREIGN KEY (`USER_ID`) REFERENCES `wb_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

use ranger;

CREATE TABLE `WB_SOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `URL` varchar(200) DEFAULT '',
  `RELATIONSHIP` varchar(200) DEFAULT '',
  `NAME` varchar(200) DEFAULT '',
  PRIMARY KEY (`ID`)
);

use ranger;


CREATE TABLE `WB_VISIBLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` int(11) DEFAULT -1,
  `LIST_ID` int(11) DEFAULT -1,
  PRIMARY KEY (`ID`)
);

use ranger;

CREATE TABLE `WB_STATUS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,  
  `STID` char(50) NOT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `CREATE_AT` datetime DEFAULT NULL,
  `MID` char(100) DEFAULT NULL,
  `ID_STR` bigint(20) DEFAULT -1,  
  `TEXT` varchar(500) DEFAULT '',
  `SR_ID` bigint(20) DEFAULT -1,
  `FAVORRITED` char(1) DEFAULT 'N',
  `TRUNCATED` char(1) DEFAULT 'N',
  `IN_REPLY_TO_STATUS_ID` bigint(20) DEFAULT -1,  
  `IN_REPLY_TO_USER_ID` bigint(20) DEFAULT -1, 
  `IN_REPLY_TO_SCREEN_NAME` varchar(100) DEFAULT NULL,
  `THUNMB_NAIL_PIC` varchar(200) DEFAULT '',
  `B_MIDDLE_PIC` varchar(200) DEFAULT '',
  `RETWEETED_STATUS_ID` bigint(20) DEFAULT -1, 
  `GEO` char(100) DEFAULT '',
  `LATITUDE` DOUBLE DEFAULT 0,
  `LONGITUDE` DOUBLE DEFAULT 0,
  `REPORTS_COUNT` int(11) DEFAULT 0,
  `COMMENTS_COUNT` int(11) DEFAULT 0,
  `ANNOTATIONS` varchar(200) DEFAULT NULL,
  `M_LEVEL` int(11) DEFAULT 0,
  `V_ID` bigint(20) DEFAULT -1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `STID_UNIQUE` (`STID`),
  CONSTRAINT `USER_ID_STATUS` FOREIGN KEY (`USER_ID`) REFERENCES `wb_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `SR_ID` FOREIGN KEY (`SR_ID`) REFERENCES `wb_source` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `IN_REPLY_TO_STATUS_ID` FOREIGN KEY (`IN_REPLY_TO_STATUS_ID`) REFERENCES `wb_status` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `IN_REPLY_TO_USER_ID` FOREIGN KEY (`IN_REPLY_TO_USER_ID`) REFERENCES `wb_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `RETWEETED_STATUS_ID` FOREIGN KEY (`RETWEETED_STATUS_ID`) REFERENCES `wb_status` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `V_ID` FOREIGN KEY (`V_ID`) REFERENCES `wb_visible` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);